address peer review feedback
OpenLiberty/draft-guide-contract-testing pull request #5
Opened 2020-12-23 21:10 UTC by meswan

2020-12-23 21:29 UTC, griffinhadfield approved these changes
LGTM

2020-12-23 21:33 UTC, AustinSeto requested changes
Just need a `.gitignore` for the `target` directories

2021-01-05 00:07 UTC, meswan commented
@AustinSeto , test scripts, gh action and .gitignore added

2021-01-05 14:41 UTC, AustinSeto approved these changes
LGTM

2021-01-05 14:57 UTC, merged